version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp\Dockerfile

  mssql-db:
    image: ${DOCKER_REGISTRY-}mssqldb
    build:
      context: .
      dockerfile: ./MSSQL-Dockerfile
      args:
        ACCEPT_EULA: ${ACCEPT_EULA}
        SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - 1433:1433
    environment:
        ACCEPT_EULA: ${ACCEPT_EULA}
        SA_PASSWORD: ${SA_PASSWORD}